### ISSUE TITLE
XE4 compatibility

### ISSUE THREAD

**Issue by edwinyzh** [sempare/sempare-delphi-template-engine#4] opened 2020-11-02 07:48 UTC
Hello,

I see this excellent library got some real nice improvements in the past year, and I tried to compile it again, with my not-quite-old XE4 :D

Unfortunately, I couldn't compile.

**Comment by sempare** [comment] 2020-11-02 10:50
Hi Edwin,

I've made a branch - xe4.

I've made some tweaks as per our last discussion - the KeepContext/RemoveContext has been removed. 

Also, the tkUnicodeString and tkWideString has been updated to use the shortened versions of those strings.

As I don't have access to XE4, could you confirm if there are any other issues?

Let me know if there are other issues. I will merge into the main branch when we have made significant progress.

**Comment by edwinyzh** [comment] 2020-11-02 15:03
Hi,

Thanks! I'll check it later.
After looked at the code a little bit, I assume there is a lot of other needs to be changed as well, IMO...
This [stackoverflow post ](https://stackoverflow.com/a/8460108/133516)should give you a idea.

Have you used old versions of Delphi BTW? Are you a new Delphi convert?
I guess the most incompatibilities lies in the use of generics and array syntax enhancements.

**Comment by sempare** [comment] 2020-11-02 15:28
Yes, there is a bit that can change. 

Re old versions of Delphi. I've used since TP 3.0, but I've always upgraded with Delphi, so never had issues with older versions. ;) Although I did a big jump from Delphi 7 to XE 8

I could appreciate that generics and RTTI could be an issue.

**Comment by edwinyzh** [comment] 2020-11-02 16:02
@sempare,

I'll definitely check it and report the issues as detail as possible.
If possible, I'll make pull requests.

**Comment by edwinyzh** [comment] 2020-11-02 16:02
@sempare,

I'll definitely check it and report the issues as detail as possible.
If possible, I'll make pull requests.

**Comment by darnocian** [comment] 2020-11-02 16:55
@edwinyzh Thanks.

I'm happy for you to provide pointers. I know there are a number of things I want to update as well. The initial objective was the functionality and the interfaces a user would use and then change focus on internals for optimisation, etc.

btw. not sure if you noticed I've dual-licensed the library. From an IP perspective, need to review the contribution process.

**Comment by edwinyzh** [comment] 2020-11-02 18:04
first try:

![2020-11-03_02h02_40](https://user-images.githubusercontent.com/541197/97902553-bf6ffa80-1d78-11eb-8b9f-458055e5bf01.png)

**Comment by edwinyzh** [comment] 2020-11-02 18:15
> btw. not sure if you noticed I've dual-licensed the library. From an IP perspective, need to review the contribution process.

just noticed that! Be sure one can easily send payment using things like paypal. I'd like to evaluate it once I get it compiled with xe4.

**Comment by sempare** [comment] 2020-11-02 19:34
with the GPL license, you are free to play with it. ;)

So I realise 2 things:
I was trying to avoid using lots of try/finally at the time. I can work that stuff out and be more traditional. 
Also, with RTTI, I think relying less on the newer RTTI but relying on the TTypeInfo may be better (and probably improve compatibility with freepascal too - the fpc rtti isn't compatable yet)
I'll unwind some of that stuff...

**Comment by darnocian** [comment] 2020-11-02 22:39
Looking at those errors from your screenshot, I definitely see there is a lot going on which relates to the RTTI...

That initial error is simple however - I suspect changing to Preseve.Value<boolean>(...) would fix that. Preseve should actually be Preserve.Value()... but anyways, that is an easy rename refactor. The issue is that Delphi is pretty poor at resolving generic types based on arguments (although it is better in later versions, it is still pretty poor at doing so).

So I must investigate the tkArray, tkDynArray,... etc. In some cases, it seems I have an array of TTypeKind. There are some statements, either 'case' or 'if value in [values..]' which from the errors listed above seem problematic... Doesn't seem too much of a problem to workaround those... but the missing or unknown TTypeKind values seem strange?

**Comment by darnocian** [comment] 2020-11-02 22:44
Ah, I spotted the issue with TTypeKind. In XE4, it is in System.TypeInfo, where in XE7 onwards, it is in System.

**Comment by darnocian** [comment] 2020-11-03 00:48
I pushed an update on the xe4 branch which should sort out the 2 issues...

**Comment by edwinyzh** [comment] 2020-11-03 05:53
@darnocian , the traditional RTTI (System.TypInfo) is much much faster than the extended RTTI, according to various tests, included the experience by the author of mORMot. And yes, it's also more FPC-compatible.

Thanks for the update, here is the compilation result with the latest revision:
![2020-11-03_13h47_48](https://user-images.githubusercontent.com/541197/97953460-861ca680-1ddb-11eb-98fc-1c9ac8b92180.png)

I guess you must use Integer for the loop control var.

BTW, I've read the document of sempare template, I really LOVE it's design - does most of the job as a template language, no unneeded complexity, but with no limited extensibility :)

**Comment by edwinyzh** [comment] 2020-11-03 06:58
More compiler errors after changed the loop control var from Int64 to Integer:
```
[dcc32 Error] Sempare.Template.Evaluate.pas(714): E2003 Undeclared identifier: 'tkAnsiString'
[dcc32 Error] Sempare.Template.Evaluate.pas(722): E2003 Undeclared identifier: 'AsVarRec'
[dcc32 Error] Sempare.Template.Parser.pas(1399): E2008 Incompatible types
[dcc32 Error] Sempare.Template.Parser.pas(1631): E2008 Incompatible types
[dcc32 Error] Sempare.Template.Functions.pas(227): E2250 There is no overloaded version of 'Split' that can be called with these arguments
[dcc32 Fatal Error] Sempare.Template.TestFor.pas(77): F1026 File not found: 'FireDAC.Comp.Client.dcu'
```

**Comment by darnocian** [comment] 2020-11-03 12:36
@edwinyzh 

I've pushed a number of updates onto the XE4 branch.

It was a little time consuming browsing between the Embarcadero documentation on the various interfaces that had some very subtle changes. 

Let me know if there is an improvement. I tried to find as much as I could related to issues.

Regards,
Conrad

**Comment by edwinyzh** [comment] 2020-11-03 13:46
Great job! 
`Sempare.Template.Tester` was compiled successfully. So was `Sempare.Template.Demo` with a small change. It's unbelievable that you can do that without an actual XE4 installation.

It seems that you disabled JSON support under XE5? Actually at least with XE4 (maybe start from D2010) we have Json support, but it belongs to the 'DBX' namespace.

Similar issue with html encoding support which is disabled under XE7. I think that can be achieved with Indy under XE7.

**Comment by darnocian** [comment] 2020-11-03 13:56
Thanks. 

I think the main thing is trying to understand what was not compatible. Luckily from the error messages you listed, there was enough to give me an idea of what to look at. Although I went a little crazy renaming variables and things along the way... the actual issues were probably 10 lines worth of changes.

So issues I came across:
- the TTypeKind constants got aliases which I preferred to use, but were obviously newer
- for loops must use the same ordinal type as that being referenced. e.g. can't have int64 variable referencing an int range. although that is supported now.
- TVarRec got moved and the TValue.AsVarRec was not supported. For templates, only a subset really is required.

Regarding the disabled features... we can look at those as separate issues with workarounds. I think with this issue, we have achieved the main compatibility objective. ;)

Regards,
Conrad

**Comment by darnocian** [comment] 2020-11-03 13:58
FYI. Another of my side projects is a cloud CI environment for Delphi using Docker. That could potentially assist in scenarios like this.

**Comment by edwinyzh** [comment] 2020-11-03 14:03
> Regarding the disabled features... we can look at those as separate issues with workarounds. I think with this issue, we have achieved the main compatibility objective. ;)

Yes, well done, although with 2 features disabled. :P

**Comment by edwinyzh** [comment] 2020-11-03 14:04
> FYI. Another of my side projects is a cloud CI environment for Delphi using Docker. That could potentially assist in scenarios like this.

Not sure if I follow... Where is the link? Thanks.

**Comment by darnocian** [comment] 2020-11-03 14:09
It is still too raw for release... objective is to allow people to install an agent that can build projects they are interested in supporting. what will happen: you would install the agent and subscribe to the project. If I made a commit, your agent would  be pickup on commit events and then run the build & test... this would allow for something like circle-ci for delphi...

**Comment by edwinyzh** [comment] 2020-11-03 14:13
Will my agent and my Delphi have to be installed in the cloud in something like a VPS, or just in my local computer?

**Comment by darnocian** [comment] 2020-11-03 14:17
No. The issue would be with licensing... I wouldn't want to break any conditions. So the agent subscribes to projects you are interested in (your own private projects, or open source on github, etc)... and it would download the source into a docker container where it can be built and tests run (without the host os being impacted). I have virtual machines with each version of Delphi that I have had over the years, so each of them are then be responsible for testing new updates without me having to manually run the tests...

**Comment by edwinyzh** [comment] 2020-11-03 14:27
Sounds cool and useful!

**Comment by darnocian** [comment] 2020-11-03 14:30
I'm going to close this. If you can raise your other suggestions for the 2 disabled features as new issues that would be great.

**Comment by darnocian** [comment] 2020-11-03 14:30
and let me know if you identify any other issues. Thanks again for trying this.

**Closed by darnocian** 2020-11-03 14:30 UTC
