### ISSUE TITLE
Add JSON and Html encoding support for XE4

### ISSUE THREAD

**Issue by edwinyzh** [sempare/sempare-delphi-template-engine#13] opened 2020-11-03 14:47 UTC
As per discussion in #4 , the JSON and html encoder support were disabled for compilers under XE5/XE7 respectively.

But those are two must-have features for a template engine, especially for web scripting :)

**Comment by darnocian** [comment] 2020-11-03 15:13
I found the JSON documentation on http://docwiki.embarcadero.com/Libraries/XE4/en/Data.DBXJSON

**Comment by darnocian** [comment] 2020-11-03 15:41
I've pushed something 'blind' again.

**Comment by edwinyzh** [comment] 2020-11-03 15:50
First compilation passed for Sempare.Template.Demo!

**Comment by darnocian** [comment] 2020-11-03 16:14
I've pushed with html encoding support from Indy. 

Note that you can define SEMPARE_TEMPLATE_INDY. I don't make the assumption it is installed.

I added some message hints about defines that can be used. They may be annoying. you can SEMPARE_TEMPLATE_BUILD_NO_HINT to disable them.

**Comment by darnocian** [comment] 2020-11-03 16:17
Actually, I'm changing that behaviour. Indy should be installed... so will allow a flag for if indy is not present

**Comment by edwinyzh** [comment] 2020-11-03 16:23
Yes, Indy is shipped with Delphi. Although I use the latest github repository, the 'Sempare.Template.Demo` got compiled after defining the `SEMPARE_TEMPLATE_INDY` directive!

Well done!

**Comment by darnocian** [comment] 2020-11-03 16:23
I'm in the process of changing that behaviour. Will push that shortly.

**Comment by darnocian** [comment] 2020-11-03 16:29
It should work by default now.

**Comment by edwinyzh** [comment] 2020-11-03 16:35
Yes, it compiles. Is it normal that the tester project emit the following failed tests?
```
Failing Tests

  Sempare.Template.TestJson.TTestTemplateJson.TestJson
  Message: Expected string true  123 value is not equal to actual   false

  Sempare.Template.Test.Arr.TTestTemplateArr.TestArray
  Message: Expected 5 6 7 8 9 10  is not equal to actual 0 1 2 3 4 5

  Sempare.Template.Test.Arr.TTestTemplateArr.TestDerefArray
  Message: Expected 123 is not equal to actual 4536912
```

**Comment by darnocian** [comment] 2020-11-03 16:38
All tests should pass. The Json may be a result of me not being able to test/debug. ;) I just assumed the existing classes behaved the same as the current ones.

**Comment by edwinyzh** [comment] 2020-11-03 16:42
BTW, was checking your website. I'm extremely interested in the mentioned `Sempare Boot VFS` project, is it something like https://github.com/billziss-gh/winfsp? I think maybe you make make a Delphi wrapper for winfsp instead of write anything new in Delphi?

**Comment by edwinyzh** [comment] 2020-11-03 16:44
One more question, did you write this template engine all by hand, or used something like YACC?
I can see the unit names are really well organized. 
This question might be stupid, but that's because I'm really not good at that area :)

**Comment by darnocian** [comment] 2020-11-03 16:45
The VFS is actually just an code like structure for files... I have an http lib that will release at some stage too - works with this template engine. the vfs allows to map onto file system, or in memory structure, or onto application resources... so if you distribute you have static files, can get them mapped into the http lib quick and easily.

**Comment by darnocian** [comment] 2020-11-03 16:46
In delphi, you can try https://github.com/dokan-dev/dokan-delphi to create a fuse like fs...

**Comment by darnocian** [comment] 2020-11-03 16:51
> One more question, did you write this template engine all by hand, or used something like YACC?
> I can see the unit names are really well organized.
> This question might be stupid, but that's because I'm really not good at that area :)

I wrote it by hand. I looked at the lex and yacc that come with fpc, but they are so old... and also state management is quite bad... I have written interpreters using Antlr (https://github.com/antlr/antlr4) before, but Delphi has very old support in antlr3.... I was thinking of making that another project... but will see

**Comment by edwinyzh** [comment] 2020-11-03 16:53
Would you add the following code to the uses clause of `Sempare.Template.TestJson`?
```
  {$IF CompilerVersion < 28}  // from XE6? backwards
    Data.DBXJSON,
  {$ENDIF}

```

**Comment by darnocian** [comment] 2020-11-03 16:55
Is that a from a warning about inline expansion?

**Comment by edwinyzh** [comment] 2020-11-03 16:56
> > One more question, did you write this template engine all by hand, or used something like YACC?
> > I can see the unit names are really well organized.
> > This question might be stupid, but that's because I'm really not good at that area :)
> 
> I wrote it by hand. I looked at the lex and yacc that come with fpc, but they are so old... and the state management in those implementations are not pretty... I have written interpreters using Antlr (https://github.com/antlr/antlr4) before, but Delphi has very old support in antlr3.... I was thinking of making that another project... but will see

Great!!! Only the hand-written code can be really beautiful and easy to read :) An excellent project you have done!

**Comment by edwinyzh** [comment] 2020-11-03 16:57
> Is that a from a warning about inline expansion?

No, `TJSonObject` will be undefined without that.

**Comment by darnocian** [comment] 2020-11-03 16:58
> No, `TJSonObject` will be undefined without that.

It should be aliased in Sempare.Template.JSON.

**Comment by edwinyzh** [comment] 2020-11-03 17:04
> In delphi, you can try https://github.com/dokan-dev/dokan-delphi to create a fuse like fs... I did something for Hadoop years back...

I know that, but you have to redistribute over 20 mb files IIRC.

**Comment by darnocian** [comment] 2020-11-03 17:04
I've pushed again as requested. I removed the hints... they are better in documentation.

**Comment by edwinyzh** [comment] 2020-11-03 17:07
> > No, `TJSonObject` will be undefined without that.
> 
> It should be aliased in Sempare.Template.JSON.

No, maybe something is wrong in the `.inc` file?
```
{$IF CompilerVersion >= 25} // from XE4 onwards
{$DEFINE SUPPORT_JSON_DBX}
{$ENDIF}

```

**Comment by darnocian** [comment] 2020-11-03 17:09
You get a compiler error, or just the test is failing?

**Comment by edwinyzh** [comment] 2020-11-03 17:09
> I've pushed again as requested. I removed the hints... they are better in documentation.

Pulled, but get the error:
`[dcc32 Fatal Error] Sempare.Template.TestJson.pas(57): F1026 File not found: 'System.JSON.dcu' (unit scope "System" indicates Win64, OSX32, Win32 only)`

**Comment by darnocian** [comment] 2020-11-03 17:14
You are on XE4 and not XE5 right?

**Comment by darnocian** [comment] 2020-11-03 17:18
Going to try something. Give me a few minutes.

**Comment by darnocian** [comment] 2020-11-03 17:24
I think I found something. I added a few other things but I actually forgot an important check on the DBX define in the Rtti unit.

**Comment by darnocian** [comment] 2020-11-03 17:41
I pushed again.

**Comment by darnocian** [comment] 2020-11-03 17:53
I am closing branch. everything merged onto dev and master. Will deal with bugs when they arise.

**Comment by edwinyzh** [comment] 2020-11-03 18:14
Pulled the latest XE4 branch, and get:
`[dcc32 Error] Sempare.Template.JSON.pas(50): E2003 Undeclared identifier: 'TJSONBool'`

**Comment by sempare** [comment] 2020-11-03 18:40
I'm going to try again. Sorry for the problems.

**Comment by sempare** [comment] 2020-11-03 18:54
What package gets used when using the DBX stuff in XE4? I'm just thinking I might need to conditionally reference that too? DbxCommonDriver?

**Comment by sempare** [comment] 2020-11-03 19:44
I've pushed again.

**Comment by edwinyzh** [comment] 2020-11-04 06:47
I guess that's because `Data.DBXJSON` doesn't have `TJSONBool`, see:
![2020-11-04_14h41_10](https://user-images.githubusercontent.com/541197/98077773-d06d5880-1eab-11eb-8d6d-4362e8c8e995.png)

I changed it as `TJSONBool = TObject;` then I get this error:
`[dcc32 Error] Sempare.Template.Rtti.pas(597): E2003 Undeclared identifier: 'GetValue'`

Then I changed it to:
`LJsonKeyVal := LJsonObject.Get(LJsonKey).JsonValue;` and I can compile.

**Comment by sempare** [comment] 2020-11-04 09:43
Excellent. I'll make a patch now. Thanks for the insight. I actually do remember that there was the special case where JsonTrue/False became based on JsonBoolean, but I think in haste I forgot yesterday when I added the DBX. ;) 

This is the joy of not having access to the compiler. ;) But thanks again for persisting...

Did the test cases improve as a result?

**Comment by sempare** [comment] 2020-11-04 10:02
I've pushed the update again. Please advise on the tests if they have proved. Thanks again for your feedback.

**Comment by edwinyzh** [comment] 2020-11-04 10:30
> I've pushed the update again. Please advise on the tests if they have improved. Thanks again for your feedback.

Polled the XE4 branch, the 'tester' project got compiled and output the following tests running result:
```
DUnitX - [Sempare.Template.Tester.exe] - Starting Tests.

..............................I.F.F............................I................
................................................................................
......

Tests Found   : 84
Tests Ignored : 2
Tests Passed  : 80
Tests Leaked  : 0
Tests Failed  : 2
Tests Errored : 0

Failing Tests

  Sempare.Template.Test.Arr.TTestTemplateArr.TestArray
  Message: Expected 5 6 7 8 9 10  is not equal to actual 0 1 2 3 4 5

  Sempare.Template.Test.Arr.TTestTemplateArr.TestDerefArray
  Message: Expected 123 is not equal to actual 4536912
```

![2020-11-04_18h28_18](https://user-images.githubusercontent.com/541197/98100415-c8251580-1ecb-11eb-9ab0-41b9b20c3686.png)

**Comment by sempare** [comment] 2020-11-04 10:36
Thats great. So we are making progress. ;)

I'll have a look at those two tests to inspect what they are doing again to check what may be the area to investigate.

**Comment by sempare** [comment] 2020-11-04 11:49
Regarding TestArray, it is interesting. In Sempare.Template.Evaluate.pas, around line 452... I try to get the minimum bound on a primitive one dimensional array with min/max bounds. Could you check if LDimOrdType is set. It looks like the MinValue for the test is not resolved as 5, which is the problem.

I just pushed again. I don't think the change will be meaningful. My previous experience with the min/max bounds is that the compiler does not store everything as it should. I raised a related quality portal issue to Embarcadero about this ages ago... So it might be a case of in XE4 it doesn't work ... and we can patch the docs and test accordingly.

I'll check the other test now.

**Comment by sempare** [comment] 2020-11-04 12:02
The other test is similar. I'm just adding another compiler directive to make these tests pass. unfortunately, I suspect that if the compiler does not store the metadata, them we have a problem and will just have to take note of that behaviour. From the template engine perspective, it is still able to enumerate the array, just the actual range is not enumerated 100% correctly. 

I'll push this update shortly.

FYI. I raised https://quality.embarcadero.com/browse/RSP-30149

**Comment by darnocian** [comment] 2020-11-04 12:32
I've pushed another update which will hopefully make the tests pass. I've updated one of the docs to take note of the behaviour. 

I will try validate that the behaviour from System.Rtti is not a bug in that layer and check if accessing the TTypeInfo rtti layer directly yields a better result. As discussed previously, using that may yield better results performance wise too.

Let me know how it goes with your testing of the library.

**Comment by edwinyzh** [comment] 2020-11-04 12:53
Latest test results:
```
Tests Found   : 84
Tests Ignored : 2
Tests Passed  : 80
Tests Leaked  : 0
Tests Failed  : 2
Tests Errored : 0

Failing Tests

  Sempare.Template.Test.Arr.TTestTemplateArr.TestArray
  Message: Expected 5 : 10 6 : 12 7 : 14 8 : 16 9 : 18 10 : 20  is not equal to
actual 0 : 10 1 : 12 2 : 14 3 : 16 4 : 18 5 : 20

  Sempare.Template.Test.Arr.TTestTemplateArr.TestDerefArray
  Message: Expected 123 is not equal to actual 4536912
```

**Comment by darnocian** [comment] 2020-11-04 12:55
It never wants to pickup the define when I want it too!

**Comment by darnocian** [comment] 2020-11-04 12:57
I spotted my mistake. I forgot the include in the test file.

**Comment by edwinyzh** [comment] 2020-11-04 12:58
> It never wants to pickup the define when I want it too! Can you please confirm with a clean/build? Just in case something was cached.

Confirmed pulled the latest, cleaned and re-build. Same result.

**Comment by darnocian** [comment] 2020-11-04 12:59
I've pushed again with the include added in the test.

**Comment by edwinyzh** [comment] 2020-11-04 13:02
Sorry to say same result:
```
Tests Found   : 84
Tests Ignored : 2
Tests Passed  : 80
Tests Leaked  : 0
Tests Failed  : 2
Tests Errored : 0

Failing Tests

  Sempare.Template.Test.Arr.TTestTemplateArr.TestArray
  Message: Expected 5 : 10 6 : 12 7 : 14 8 : 16 9 : 18 10 : 20  is not equal to
actual 0 : 10 1 : 12 2 : 14 3 : 16 4 : 18 5 : 20

  Sempare.Template.Test.Arr.TTestTemplateArr.TestDerefArray
  Message: Expected 123 is not equal to actual 4536912
```

**Comment by edwinyzh** [comment] 2020-11-04 13:08
@darnocian BTW, this is my first time "real-time chatting" in a github issue, it's really a good communication tool, isn't it :)

**Comment by darnocian** [comment] 2020-11-04 13:08
haha. It is funny.

**Comment by darnocian** [comment] 2020-11-04 13:09
I can do discord, or slack as alternatives?

**Comment by edwinyzh** [comment] 2020-11-04 13:09
I think here is better - everything is connected.

**Comment by darnocian** [comment] 2020-11-04 13:11
did the last update improve things? 

RE chat: I'm impressed that the page refreshes actually.

**Comment by edwinyzh** [comment] 2020-11-04 13:11
While we should discuss this specific here, but maybe you can add my wechat? It's ruuxjkl (I'll deleted it once you added me)

**Comment by edwinyzh** [comment] 2020-11-04 13:13
> did the last update improve things?
> 
> RE chat: I'm impressed that the page refreshes actually.

Yes, impressed! Did you notice the (1) appendix in the Chrome tab.

**Comment by edwinyzh** [comment] 2020-11-04 13:14
> did the last update improve things?
No new changes in the xe4 branch since my last reported result?

**Comment by darnocian** [comment] 2020-11-04 13:16
Sempare.Template.Test.Arr.pas should have the include {$I 'Sempare.Template.Compiler.inc'} now...

**Comment by edwinyzh** [comment] 2020-11-04 13:35
> Sempare.Template.Test.Arr.pas should have the include {$I 'Sempare.Template.Compiler.inc'} now...

Yes, the latest report above was built with the revision that's already have that line.

**Comment by darnocian** [comment] 2020-11-04 13:53
I'm checking it now. My host machine just died on me unfortunately, so restarting the VM...

**Comment by darnocian** [comment] 2020-11-04 14:01
Ah. I made a silly mistake again. {$IF BROKEN_ARRAY_BOUNDS} vs {$IFDEF BROKEN_ARRAY_BOUNDS}

**Comment by darnocian** [comment] 2020-11-04 14:03
I pushed the update.

**Comment by edwinyzh** [comment] 2020-11-04 14:22
All passed now!
```
Tests Found   : 84
Tests Ignored : 2
Tests Passed  : 82
Tests Leaked  : 0
Tests Failed  : 0
Tests Errored : 0
```

**Comment by darnocian** [comment] 2020-11-04 14:28
Great. I'll merge and close this issue then.

Thanks again for your assistance in testing with XE4!

**Closed** 2020-11-04 14:36 UTC
